// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtCM_9AmbtmRe7DBfkZMEfHZJEo7k8TGA',
    appId: '1:72598500346:web:da66296eea10d94bffea43',
    messagingSenderId: '72598500346',
    projectId: 'notec-dam',
    authDomain: 'notec-dam.firebaseapp.com',
    storageBucket: 'notec-dam.appspot.com',
    measurementId: 'G-29F3M6WBSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnY3uoggV5ISIYZP2FKIj68bmvr9QnL0c',
    appId: '1:72598500346:android:bac13accbcbc7da3ffea43',
    messagingSenderId: '72598500346',
    projectId: 'notec-dam',
    storageBucket: 'notec-dam.appspot.com',
  );
}
